<?php

namespace AppBundle\Repository;

/**
 * GroopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroopRepository extends \Doctrine\ORM\EntityRepository
{
}
